//go:build integration

package integration

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/rudi-bruchez/argosql/internal/model"
)

// TestExports compares the real bytes of asq's own SQL and XML export
// artifacts - written by the real compiled binary, through Lab.Run,
// never by calling internal/diagnostics or internal/plan directly -
// against the exact UTF-8 value the same object reads back as via
// lab.Admin. Every comparison here is full-byte-sequence, never a
// length-only check: a formatting function that silently became the
// identity, or an encoder that dropped a trailing byte, would still
// report a plausible length but fail a byte comparison.
func TestExports(t *testing.T) {
	lab := NewLab(t, os.Getenv("ASQ_TEST_IMAGE"))
	ctx, cancel := context.WithTimeout(context.Background(), flushPollBudget)
	defer cancel()

	var major int
	if err := lab.Admin.QueryRowContext(ctx, "SELECT CAST(SERVERPROPERTY('ProductMajorVersion') AS int)").Scan(&major); err != nil {
		t.Fatalf("reading engine major version: %v", err)
	}
	logEngineIdentity(t, lab, major)

	t.Run("sql_module_definition", func(t *testing.T) {
		result, code := lab.Run(t, "S", []string{"obj", "code", "dbo.PlainModule"})
		if code != 0 {
			t.Fatalf("obj code dbo.PlainModule: got exit code %d, want 0 (error=%+v)", code, result.Error)
		}
		artifact := artifactOfKind(t, result, "module_definition")
		exported, err := os.ReadFile(artifact.Path)
		if err != nil {
			t.Fatalf("reading exported module artifact %q: %v", artifact.Path, err)
		}

		var want string
		if err := lab.Admin.QueryRowContext(ctx,
			"SELECT definition FROM sys.sql_modules WHERE object_id = OBJECT_ID(N'dbo.PlainModule')",
		).Scan(&want); err != nil {
			t.Fatalf("reading sys.sql_modules.definition directly: %v", err)
		}

		if !bytes.Equal(exported, []byte(want)) {
			t.Fatalf("exported module definition differs byte for byte from sys.sql_modules.definition:\nexported (%d bytes): %q\nadmin    (%d bytes): %q",
				len(exported), exported, len(want), want)
		}
	})

	t.Run("plan_xml", func(t *testing.T) {
		queryID := lab.QueryID(t, "AsqExportsMarker")
		planID := planIDFor(ctx, t, lab, queryID)

		result, code := lab.Run(t, "S", []string{"plan", fmt.Sprintf("%d", queryID), "--plan-id", fmt.Sprintf("%d", planID)})
		if code != 0 {
			t.Fatalf("plan %d --plan-id %d: got exit code %d, want 0 (error=%+v)", queryID, planID, code, result.Error)
		}
		artifact := artifactOfKind(t, result, "plan_xml")
		exported, err := os.ReadFile(artifact.Path)
		if err != nil {
			t.Fatalf("reading exported plan artifact %q: %v", artifact.Path, err)
		}

		var want string
		if err := lab.Admin.QueryRowContext(ctx,
			"SELECT query_plan FROM sys.query_store_plan WHERE query_id = @p1 AND plan_id = @p2", queryID, planID,
		).Scan(&want); err != nil {
			t.Fatalf("reading sys.query_store_plan.query_plan directly: %v", err)
		}

		// NormalizeXML (internal/plan/xml.go) only ever rewrites a leading
		// declaration's own encoding attribute when it names something
		// other than UTF-8; a plan generated by this project's own
		// fixtures never does (CLAUDE.md's own measured fact: "environ
		// 4 500 octets, sans aucun CRLF ni caractère non ASCII"), so the
		// exported bytes and the driver's own UTF-8 string must match
		// exactly here, with no normalization in play to account for.
		if !bytes.Equal(exported, []byte(want)) {
			t.Fatalf("exported plan XML differs byte for byte from sys.query_store_plan.query_plan:\nexported (%d bytes)\nadmin    (%d bytes)\nfirst difference search: exported[:200]=%q admin[:200]=%q",
				len(exported), len(want), firstN(exported, 200), firstN([]byte(want), 200))
		}
	})
}

// artifactOfKind returns the first Complete artifact of the given kind
// in result, failing the test if none exists.
func artifactOfKind(t *testing.T, result model.Result, kind string) model.Artifact {
	t.Helper()
	for _, a := range result.Artifacts {
		if a.Kind == kind && a.Complete {
			return a
		}
	}
	t.Fatalf("no complete artifact of kind %q in result.Artifacts: %+v", kind, result.Artifacts)
	return model.Artifact{}
}

func firstN(b []byte, n int) []byte {
	if len(b) <= n {
		return b
	}
	return b[:n]
}
